# Generated by Django 6.0.2 on 2026-03-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_user_in_game_remove_user_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('party_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC')),
                ('current_round', models.IntegerField(default=1)),
                ('round_time', models.IntegerField(default=1)),
                ('total_rounds', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.TimeField(auto_now_add=True)),
                ('left_at', models.TimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_index', models.IntegerField(default=1)),
                ('round_status', models.CharField(choices=[('INITIALIZING CONTEXT', 'Initializing context'), ('DRAWING', 'Drawing'), ('GUESSING', 'Guessing')], default='INITIALIZING CONTEXT')),
                ('started_at', models.TimeField(auto_now_add=True)),
                ('finished_at', models.TimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='game.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_entry', models.CharField(choices=[('A CONTEXT', 'A context'), ('A GUESS', 'A guess'), ('A DRAWING', 'A drawing')])),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to='users.user')),
                ('in_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_entry', to='game.round')),
            ],
        ),
    ]
