# Generated by Django 6.0.2 on 2026-03-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
        migrations.AlterModelTable(
            name='party',
            table='party',
        ),
        migrations.AlterModelTable(
            name='partymember',
            table='party_member',
        ),
        migrations.AlterModelTable(
            name='round',
            table='round',
        ),
    ]
