# Generated by Django 6.0.2 on 2026-02-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('inGame', models.BooleanField(default=False)),
                ('isOnline', models.BooleanField(default=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
