# Generated by Django 6.0.2 on 2026-03-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_lastlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inGame',
            new_name='in_game',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isOnline',
            new_name='is_online',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastLogin',
            new_name='last_login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
