# Generated by Django 6.0.2 on 2026-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_createdat_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='in_game',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DRAWING', 'Drawing'), ('GUESSING', 'Guessing')], default='OFFLINE', max_length=255),
        ),
    ]
