# Generated by Django 6.0.2 on 2026-03-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_ingame_user_in_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
