# Generated by Django 6.0.2 on 2026-03-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_entry_table_alter_party_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='left_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.party'),
        ),
    ]
