# Generated by Django 6.0.2 on 2026-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_partymember_left_at_alter_partymember_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='current_players',
            field=models.IntegerField(default=1, max_length=6),
        ),
        migrations.AddField(
            model_name='party',
            name='max_players',
            field=models.IntegerField(default=6, max_length=6),
        ),
    ]
