# Generated by Django 6.0.2 on 2026-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_party_current_players_party_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
